apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jvw90jqhg-nodejs 
  janus-idp.io/tekton: jvw90jqhg-nodejs
  backstage.io/kubernetes-id: jvw90jqhg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvw90jqhg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  