apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jvw90jqhg-nodejs
  janus-idp.io/tekton: jvw90jqhg-nodejs
  backstage.io/kubernetes-id: jvw90jqhg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvw90jqhg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
